// angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
    LucideAngularModule,
    LayoutDashboard,
    CreditCard,
    History,
    Plane,
    Gift,
    Settings,
    Search,
    Bell,
    User,
    ArrowUpRight,
    ArrowRight
} from 'lucide-angular';

@Component({
    selector: 'app-root',
    standalone: true,
    imports: [CommonModule, LucideAngularModule],
    templateUrl: './app.component.html',
    styleUrls: []
})
export class AppComponent {
    readonly LayoutDashboard = LayoutDashboard;
    readonly CreditCard = CreditCard;
    readonly History = History;
    readonly Plane = Plane;
    readonly Gift = Gift;
    readonly Settings = Settings;
    readonly Search = Search;
    readonly Bell = Bell;
    readonly User = User;
    readonly ArrowUpRight = ArrowUpRight;
    readonly ArrowRight = ArrowRight;

    transactions = [
        { name: 'Delta Air Lines', category: 'Travel', date: 'Feb 04, 2026', amount: '$425.00', status: 'Processed' },
        { name: 'The Grill NYC', category: 'Dining', date: 'Feb 03, 2026', amount: '$182.40', status: 'Processed' },
        { name: 'Apple Store', category: 'Shopping', date: 'Jan 31, 2026', amount: '$1,299.00', status: 'Processed' },
        { name: 'Whole Foods', category: 'Shopping', date: 'Jan 28, 2026', amount: '$64.20', status: 'Processed' }
    ];
}

<div class="app-container">
    <!-- Sidebar -->
    <aside class="sidebar">
        <div class="logo">
            <div
                style="width: 32px; height: 32px; background: var(--primary); border-radius: 6px; display: flex; align-items: center; justify-content: center; font-weight: bold;">
                A</div>
            <span>AMEX GLOBAL</span>
        </div>

        <nav class="nav-links">
            <a href="#" class="nav-link active">
                <lucide-icon [name]="LayoutDashboard" [size]="20"></lucide-icon>
                Dashboard
            </a>
            <a href="#" class="nav-link">
                <lucide-icon [name]="CreditCard" [size]="20"></lucide-icon>
                My Cards
            </a>
            <a href="#" class="nav-link">
                <lucide-icon [name]="History" [size]="20"></lucide-icon>
                Transactions
            </a>
            <a href="#" class="nav-link">
                <lucide-icon [name]="Gift" [size]="20"></lucide-icon>
                Rewards
            </a>
            <a href="#" class="nav-link">
                <lucide-icon [name]="Plane" [size]="20"></lucide-icon>
                Travel & Lifestyle
            </a>
            <div style="margin-top: auto; padding-top: 2rem;">
                <a href="#" class="nav-link">
                    <lucide-icon [name]="Settings" [size]="20"></lucide-icon>
                    Settings
                </a>
            </div>
        </nav>
    </aside>

    <!-- Header -->
    <header class="header">
        <div class="search-bar">
            <lucide-icon [name]="Search" [size]="18" style="color: var(--text-muted);"></lucide-icon>
            <input type="text" placeholder="Search transactions, offers..." />
        </div>

        <div style="display: flex; align-items: center; gap: 1.5rem;">
            <button style="background: none; border: none; cursor: pointer; position: relative;">
                <lucide-icon [name]="Bell" [size]="22" style="color: var(--secondary);"></lucide-icon>
                <span
                    style="position: absolute; top: 0; right: 0; width: 8px; height: 8px; background: #ef4444; border-radius: 50%; border: 2px solid white;"></span>
            </button>

            <div
                style="display: flex; align-items: center; gap: 0.75rem; padding-left: 1rem; border-left: 1px solid var(--border);">
                <div style="text-align: right;">
                    <p style="font-size: 0.9rem; font-weight: 600;">Alex Thompson</p>
                    <p style="font-size: 0.75rem; color: var(--text-muted);">Platinum Member</p>
                </div>
                <div
                    style="width: 40px; height: 40px; background: var(--primary); border-radius: 50%; display: flex; align-items: center; justify-content: center; color: white;">
                    <lucide-icon [name]="User" [size]="20"></lucide-icon>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <main class="main-content">
        <div class="premium-banner">
            <div style="position: relative; z-index: 2;">
                <h1 style="font-size: 2rem; margin-bottom: 0.5rem;">Welcome back, Alex</h1>
                <p style="opacity: 0.9; margin-bottom: 1.5rem;">You have 3 new offers tailored to your travel interests.
                </p>
                <button class="btn btn-primary" style="background: white; color: var(--primary);">
                    View Personalized Plan
                </button>
            </div>
        </div>

        <div class="stats-grid">
            <!-- Card 1 -->
            <div class="card">
                <div style="display: flex; justify-content: space-between; margin-bottom: 1.5rem;">
                    <span style="color: var(--text-muted); font-weight: 500;">Platinum Card Balance</span>
                    <lucide-icon [name]="CreditCard" [size]="20" style="color: var(--primary);"></lucide-icon>
                </div>
                <h2 style="font-size: 1.75rem; font-weight: 700; margin-bottom: 0.5rem;">$4,285.50</h2>
                <div style="display: flex; align-items: center; gap: 0.5rem; color: #1a7f37; font-size: 0.9rem;">
                    <lucide-icon [name]="ArrowUpRight" [size]="16"></lucide-icon>
                    <span>+12% from last month</span>
                </div>
                <img src="assets/card.png" alt="Amex Platinum" class="card-img" />
                <div style="margin-top: 1.5rem; display: flex; gap: 0.5rem;">
                    <button class="btn btn-primary" style="flex: 1;">Pay Bill</button>
                    <button class="btn" style="background: var(--bg); color: var(--secondary); flex: 1;">Manage</button>
                </div>
            </div>

            <!-- Card 2 -->
            <div class="card">
                <div style="display: flex; justify-content: space-between; margin-bottom: 1.5rem;">
                    <span style="color: var(--text-muted); font-weight: 500;">Membership Rewards</span>
                    <lucide-icon [name]="Gift" [size]="20" style="color: #e67e22;"></lucide-icon>
                </div>
                <h2 style="font-size: 1.75rem; font-weight: 700; margin-bottom: 0.5rem;">124,500</h2>
                <p style="color: var(--text-muted); font-size: 0.9rem; margin-bottom: 1.5rem;">Points available to
                    redeem</p>

                <div style="background: var(--bg); padding: 1rem; border-radius: var(--radius); margin-bottom: 1rem;">
                    <p style="font-size: 0.85rem; font-weight: 600; margin-bottom: 0.5rem;">Recent Earnings</p>
                    <div style="display: flex; justify-content: space-between; font-size: 0.85rem;">
                        <span>Delta Air Lines (5x)</span>
                        <span style="color: var(--primary); font-weight: 700;">+1,250 pts</span>
                    </div>
                </div>

                <div style="display: flex; flex-direction: column; gap: 0.75rem;">
                    <button class="btn" style="border: 1px solid var(--primary); color: var(--primary);">Explore
                        Rewards</button>
                    <button class="btn" style="background: var(--bg); color: var(--secondary);">Transfer Points</button>
                </div>
            </div>

            <!-- Card 3 -->
            <div class="card">
                <div style="display: flex; justify-content: space-between; margin-bottom: 1.5rem;">
                    <span style="color: var(--text-muted); font-weight: 500;">Travel & Lifestyle</span>
                    <lucide-icon [name]="Plane" [size]="20" style="color: var(--accent);"></lucide-icon>
                </div>
                <div class="offer-card">
                    <img src="assets/luxury.png" alt="Luxury Travel" />
                    <div class="offer-overlay"></div>
                    <div class="offer-content">
                        <h3 style="font-size: 1.1rem; margin-bottom: 0.25rem;">Luxury Escape</h3>
                        <p style="font-size: 0.8rem; opacity: 0.9;">Exclusive 20% off at Ritz-Carlton Paris</p>
                        <button
                            style="background: none; border: none; color: white; display: flex; align-items: center; gap: 0.5rem; margin-top: 0.75rem; font-weight: 600; cursor: pointer;">
                            Book Now <lucide-icon [name]="ArrowRight" [size]="16"></lucide-icon>
                        </button>
                    </div>
                </div>
                <div style="display: flex; align-items: center; justify-content: space-between; margin-top: 1rem;">
                    <p style="font-size: 0.85rem; color: var(--text-muted);">Next Trip: New York (Mar 12)</p>
                    <button class="btn" style="padding: 0.4rem 0.8rem; font-size: 0.8rem; background: var(--bg);">View
                        Trip</button>
                </div>
            </div>
        </div>

        <div class="grid-cols-2">
            <!-- Transactions -->
            <div class="card">
                <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 1.5rem;">
                    <h3 style="font-size: 1.25rem;">Recent Transactions</h3>
                    <button
                        style="color: var(--primary); background: none; border: none; font-weight: 600; cursor: pointer;">View
                        All</button>
                </div>
                <div class="transaction-list">
                    <div *ngFor="let item of transactions" class="transaction-item">
                        <div style="display: flex; align-items: center; gap: 1rem;">
                            <div
                                style="width: 40px; height: 40px; background: var(--bg); border-radius: 10px; display: flex; align-items: center; justify-content: center;">
                                <lucide-icon *ngIf="item.category === 'Travel'" [name]="Plane" [size]="20"
                                    style="color: var(--primary);"></lucide-icon>
                                <lucide-icon *ngIf="item.category === 'Dining'" [name]="Gift" [size]="20"
                                    style="color: #e67e22;"></lucide-icon>
                                <lucide-icon *ngIf="item.category === 'Shopping'" [name]="CreditCard" [size]="20"
                                    style="color: #9b59b6;"></lucide-icon>
                            </div>
                            <div>
                                <p style="font-weight: 600;">{{ item.name }}</p>
                                <p style="font-size: 0.8rem; color: var(--text-muted);">{{ item.date }} • {{
                                    item.category }}</p>
                            </div>
                        </div>
                        <div style="text-align: right;">
                            <p style="font-weight: 700;">{{ item.amount }}</p>
                            <span class="status-badge status-success">{{ item.status }}</span>
                        </div>
                    </div>
                </div>
            </div>

            <!-- AI Insights -->
            <div class="card">
                <h3 style="font-size: 1.25rem; margin-bottom: 1.5rem;">AI Spending Insights</h3>
                <div style="text-align: center; padding: 1rem;">
                    <div
                        style="width: 120px; height: 120px; border-radius: 50%; border: 8px solid var(--bg); border-top-color: var(--primary); margin: 0 auto 1.5rem; display: flex; align-items: center; justify-content: center;">
                        <div style="text-align: center;">
                            <p style="font-size: 1.25rem; font-weight: 700;">65%</p>
                            <p style="font-size: 0.7rem; color: var(--text-muted);">of limit</p>
                        </div>
                    </div>
                    <p style="font-size: 0.9rem; color: var(--text-muted); margin-bottom: 1.5rem;">
                        Your travel spending is <span style="font-weight: 700;">lower</span> than usual this month. You
                        have <span style="font-weight: 700;">$1,200</span> more available for your next trip.
                    </p>
                    <div style="display: flex; flex-direction: column; gap: 0.75rem;">
                        <div
                            style="border-bottom: 1px solid var(--border); padding-bottom: 0.75rem; display: flex; justify-content: space-between; font-size: 0.9rem;">
                            <span>Projected Balance</span>
                            <span style="font-weight: 600;">$5,100</span>
                        </div>
                        <div
                            style="padding-bottom: 0.75rem; display: flex; justify-content: space-between; font-size: 0.9rem;">
                            <span>Savings Goal</span>
                            <span style="font-weight: 600; color: #1a7f37;">+ $340</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>

// src/App.jsx
import React, { useState } from 'react';
import {
  LayoutDashboard,
  CreditCard,
  History,
  Plane,
  Gift,
  Settings,
  Search,
  Bell,
  User,
  ArrowUpRight,
  Plus,
  ArrowRight
} from 'lucide-react';
import { motion } from 'framer-motion';

const Sidebar = () => (
  <aside className="sidebar">
    <div className="logo">
      <div style={{ width: 32, height: 32, background: 'var(--primary)', borderRadius: '6px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 'bold' }}>A</div>
      <span>AMEX GLOBAL</span>
    </div>

    <nav className="nav-links">
      <a href="#" className="nav-link active">
        <LayoutDashboard size={20} />
        Dashboard
      </a>
      <a href="#" className="nav-link">
        <CreditCard size={20} />
        My Cards
      </a>
      <a href="#" className="nav-link">
        <History size={20} />
        Transactions
      </a>
      <a href="#" className="nav-link">
        <Gift size={20} />
        Rewards
      </a>
      <a href="#" className="nav-link">
        <Plane size={20} />
        Travel & Lifestyle
      </a>
      <div style={{ marginTop: 'auto', paddingTop: '2rem' }}>
        <a href="#" className="nav-link">
          <Settings size={20} />
          Settings
        </a>
      </div>
    </nav>
  </aside>
);

const Header = () => (
  <header className="header">
    <div className="search-bar">
      <Search size={18} color="var(--text-muted)" />
      <input type="text" placeholder="Search transactions, offers..." />
    </div>

    <div style={{ display: 'flex', alignItems: 'center', gap: '1.5rem' }}>
      <button style={{ background: 'none', border: 'none', cursor: 'pointer', position: 'relative' }}>
        <Bell size={22} color="var(--secondary)" />
        <span style={{ position: 'absolute', top: 0, right: 0, width: 8, height: 8, background: '#ef4444', borderRadius: '50%', border: '2px solid white' }}></span>
      </button>

      <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', paddingLeft: '1rem', borderLeft: '1px solid var(--border)' }}>
        <div style={{ textAlign: 'right' }}>
          <p style={{ fontSize: '0.9rem', fontWeight: 600 }}>Alex Thompson</p>
          <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Platinum Member</p>
        </div>
        <div style={{ width: 40, height: 40, background: 'var(--primary)', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'white' }}>
          <User size={20} />
        </div>
      </div>
    </div>
  </header>
);

const TransactionItem = ({ name, category, date, amount, status }) => (
  <div className="transaction-item">
    <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
      <div style={{ width: 40, height: 40, background: 'var(--bg)', borderRadius: '10px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        {category === 'Travel' && <Plane size={20} color="var(--primary)" />}
        {category === 'Dining' && <Gift size={20} color="#e67e22" />}
        {category === 'Shopping' && <CreditCard size={20} color="#9b59b6" />}
      </div>
      <div>
        <p style={{ fontWeight: 600 }}>{name}</p>
        <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>{date} • {category}</p>
      </div>
    </div>
    <div style={{ textAlign: 'right' }}>
      <p style={{ fontWeight: 700 }}>{amount}</p>
      <span className="status-badge status-success">{status}</span>
    </div>
  </div>
);

function App() {
  const containerVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: {
      opacity: 1,
      y: 0,
      transition: { duration: 0.6, staggerChildren: 0.1 }
    }
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 10 },
    visible: { opacity: 1, y: 0 }
  };

  return (
    <div className="app-container">
      <Sidebar />
      <Header />

      <main className="main-content">
        <motion.div
          variants={containerVariants}
          initial="hidden"
          animate="visible"
        >
          <motion.div variants={itemVariants} className="premium-banner">
            <div style={{ position: 'relative', zIndex: 2 }}>
              <h1 style={{ fontSize: '2rem', marginBottom: '0.5rem' }}>Welcome back, Alex</h1>
              <p style={{ opacity: 0.9, marginBottom: '1.5rem' }}>You have 3 new offers tailored to your travel interests.</p>
              <button className="btn btn-primary" style={{ background: 'white', color: 'var(--primary)' }}>
                View Personalized Plan
              </button>
            </div>
          </motion.div>

          <div className="stats-grid">
            <motion.div variants={itemVariants} className="card">
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '1.5rem' }}>
                <span style={{ color: 'var(--text-muted)', fontWeight: 500 }}>Platinum Card Balance</span>
                <CreditCard size={20} color="var(--primary)" />
              </div>
              <h2 style={{ fontSize: '1.75rem', fontWeight: 700, marginBottom: '0.5rem' }}>$4,285.50</h2>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: '#1a7f37', fontSize: '0.9rem' }}>
                <ArrowUpRight size={16} />
                <span>+12% from last month</span>
              </div>
              <img src="/card.png" alt="Amex Platinum" className="card-img" />
              <div style={{ marginTop: '1.5rem', display: 'flex', gap: '0.5rem' }}>
                <button className="btn btn-primary" style={{ flex: 1 }}>Pay Bill</button>
                <button className="btn" style={{ background: 'var(--bg)', color: 'var(--secondary)', flex: 1 }}>Manage</button>
              </div>
            </motion.div>

            <motion.div variants={itemVariants} className="card">
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '1.5rem' }}>
                <span style={{ color: 'var(--text-muted)', fontWeight: 500 }}>Membership Rewards</span>
                <Gift size={20} color="#e67e22" />
              </div>
              <h2 style={{ fontSize: '1.75rem', fontWeight: 700, marginBottom: '0.5rem' }}>124,500</h2>
              <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', marginBottom: '1.5rem' }}>Points available to redeem</p>

              <div style={{ background: 'var(--bg)', padding: '1rem', borderRadius: 'var(--radius)', marginBottom: '1rem' }}>
                <p style={{ fontSize: '0.85rem', fontWeight: 600, marginBottom: '0.5rem' }}>Recent Earnings</p>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem' }}>
                  <span>Delta Air Lines (5x)</span>
                  <span style={{ color: 'var(--primary)', fontWeight: 700 }}>+1,250 pts</span>
                </div>
              </div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                <button className="btn" style={{ border: '1px solid var(--primary)', color: 'var(--primary)' }}>Explore Rewards</button>
                <button className="btn" style={{ background: 'var(--bg)', color: 'var(--secondary)' }}>Transfer Points</button>
              </div>
            </motion.div>

            <motion.div variants={itemVariants} className="card">
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '1.5rem' }}>
                <span style={{ color: 'var(--text-muted)', fontWeight: 500 }}>Travel & Lifestyle</span>
                <Plane size={20} color="var(--accent)" />
              </div>
              <div className="offer-card">
                <img src="/luxury.png" alt="Luxury Travel" />
                <div className="offer-overlay"></div>
                <div className="offer-content">
                  <h3 style={{ fontSize: '1.1rem', marginBottom: '0.25rem' }}>Luxury Escape</h3>
                  <p style={{ fontSize: '0.8rem', opacity: 0.9 }}>Exclusive 20% off at Ritz-Carlton Paris</p>
                  <button style={{ background: 'none', border: 'none', color: 'white', display: 'flex', alignItems: 'center', gap: '0.5rem', marginTop: '0.75rem', fontWeight: 600, cursor: 'pointer' }}>
                    Book Now <ArrowRight size={16} />
                  </button>
                </div>
              </div>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginTop: '1rem' }}>
                <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>Next Trip: New York (Mar 12)</p>
                <button className="btn" style={{ padding: '0.4rem 0.8rem', fontSize: '0.8rem', background: 'var(--bg)' }}>View Trip</button>
              </div>
            </motion.div>
          </div>

          <div className="grid-cols-2">
            <motion.div variants={itemVariants} className="card">
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
                <h3 style={{ fontSize: '1.25rem' }}>Recent Transactions</h3>
                <button style={{ color: 'var(--primary)', background: 'none', border: 'none', fontWeight: 600, cursor: 'pointer' }}>View All</button>
              </div>
              <div className="transaction-list">
                <TransactionItem
                  name="Delta Air Lines"
                  category="Travel"
                  date="Feb 04, 2026"
                  amount="$425.00"
                  status="Processed"
                />
                <TransactionItem
                  name="The Grill NYC"
                  category="Dining"
                  date="Feb 03, 2026"
                  amount="$182.40"
                  status="Processed"
                />
                <TransactionItem
                  name="Apple Store"
                  category="Shopping"
                  date="Jan 31, 2026"
                  amount="$1,299.00"
                  status="Processed"
                />
                <TransactionItem
                  name="Whole Foods"
                  category="Shopping"
                  date="Jan 28, 2026"
                  amount="$64.20"
                  status="Processed"
                />
              </div>
            </motion.div>

            <motion.div variants={itemVariants} className="card">
              <h3 style={{ fontSize: '1.25rem', marginBottom: '1.5rem' }}>AI Spending Insights</h3>
              <div style={{ textAlign: 'center', padding: '1rem' }}>
                <div style={{ width: 120, height: 120, borderRadius: '50%', border: '8px solid var(--bg)', borderTopColor: 'var(--primary)', margin: '0 auto 1.5rem', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  <div style={{ textAlign: 'center' }}>
                    <p style={{ fontSize: '1.25rem', fontWeight: 700 }}>65%</p>
                    <p style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>of limit</p>
                  </div>
                </div>
                <p style={{ fontSize: '0.9rem', color: 'var(--text-muted)', marginBottom: '1.5rem' }}>
                  Your travel spending is <span style={{ fontWeight: 700 }}>lower</span> than usual this month. You have <span style={{ fontWeight: 700 }}>$1,200</span> more available for your next trip.
                </p>
                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                  <div style={{ borderBottom: '1px solid var(--border)', paddingBottom: '0.75rem', display: 'flex', justifyContent: 'space-between', fontSize: '0.9rem' }}>
                    <span>Projected Balance</span>
                    <span style={{ fontWeight: 600 }}>$5,100</span>
                  </div>
                  <div style={{ paddingBottom: '0.75rem', display: 'flex', justifyContent: 'space-between', fontSize: '0.9rem' }}>
                    <span>Savings Goal</span>
                    <span style={{ fontWeight: 600, color: '#1a7f37' }}>+ $340</span>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>
        </motion.div>
      </main>
    </div >
  );
}

export default App;
